services:
  - type: web
    name: tour-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/tour-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://<YOUR_DB_HOST>:5432/tour
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: bm040321
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin
